version: 1
# Your module version - must be changed to release a new version
module_version: 0.1.6

# Any default settings that should be used for all test cases
test_defaults:
  before_init: ["terraform fmt -check"]

# The set of tests to run to verify your module works correctly
tests:
  - name: Test the module with 0.12.31
    project_root: examples
    id: test-0.12.31
    terraform_version: 0.12.31

  - name: Test the module with 0.13.7
    project_root: examples
    terraform_version: 0.13.7
    depends_on: ["test-0.12.31"]
