version: 1
# Your module version - must be changed to release a new version
module_version: 0.1.2

# Any default settings that should be used for all test cases
test_defaults:
  before_init: ["terraform fmt -check"]

# The set of tests to run to verify your module works correctly
tests:
  - name: Test the module with 0.12.31
    project_root: examples
    terraform_version: 0.12.31

  - name: Test the submodule with 0.13.0
    # project_root can be set if your test case is not stored in the root directory
    project_root: examples
    terraform_version: 0.13.0

  - name: Ensure that the submodule can fail
    # You can use negative to indicate that the test case is expected to fail
    negative: true
    project_root: examples
    terraform_version: 0.13.0
